# Generated by Django 5.2 on 2025-06-04 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='refundrequest',
            name='reason_detail',
            field=models.CharField(default=0, max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='refundrequest',
            name='reason',
            field=models.CharField(choices=[('event_cancelled', 'El evento fue cancelado'), ('could_not_attend', 'No pude asistir'), ('payment_error', 'Error en el pago'), ('other', 'Otro')], max_length=50),
        ),
    ]
