# Generated by Django 5.2 on 2025-06-17 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_user_managers_remove_user_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='total_rating',
            field=models.IntegerField(default=0),
        ),
    ]
