# Generated by Django 4.2.11 on 2025-06-25 01:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_event_total_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='total_rating',
        ),
        migrations.AddField(
            model_name='event',
            name='_tickets_updated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='notification',
            name='recipients',
            field=models.ManyToManyField(blank=True, related_name='notifications_received', through='app.Notification_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='refundrequest',
            name='approved',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='refundrequest',
            name='reason_detail',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_code',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
