# Generated by Django 5.2 on 2025-05-30 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_category_notification_venue_event_total_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='images/events'),
        ),
        migrations.AddField(
            model_name='venue',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='images/venues'),
        ),
    ]
