# Generated by Django 5.2 on 2025-05-30 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_event_imagen_venue_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='app/media/images/events'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='app/media/images/venues'),
        ),
    ]
