# Generated by Django 5.2.1 on 2025-06-01 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_event_imagen_alter_venue_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='is_read',
        ),
    ]
