# Generated by Django 5.2 on 2025-06-01 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_remove_notification_is_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='events/'),
        ),
    ]
